packaging_format = 2

id = "hash-calendar"
name = "hash-calendar"
description.en = "Lightweight calendar app where the data lives in the URL hash"
description.fr = "Application légère de calendrier où les données résident dans le hash d'URL"

version = "2026.05.17~ynh1"

maintainers = ["oleole39"]

[upstream]
license = "MIT"
demo = "https://hash-calendar.netlify.app"
userdoc = "https://github.com/supunlakmal/hash-calendar?tab=readme-ov-file#json-bridge-jsonhtml"
code = "https://github.com/supunlakmal/hash-calendar"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "20M"
ram.build = "0M"
ram.runtime = "0M"


[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/hash-calendar"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/supunlakmal/hash-calendar/archive/130b07143213f20b5d465727be56eb4ee4e9d908.tar.gz"
        sha256 = "35d0b6ff27685e4c294b4112b2bacb12d0a0e578532955312fc32d546d43013f"
        extract = true
        in_subdir = true
        autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"
