packaging_format = 2

id = "hash-calendar"
name = "hash-calendar"
description.en = "Lightweight calendar app where the data lives in the URL hash"
description.fr = "Application légère de calendrier où les données résident dans le hash d'URL"

version = "2026.02.16~ynh1"

maintainers = ["oleole39"]

[upstream]
license = "MIT"
demo = "https://hash-calendar.netlify.app"
userdoc = "https://github.com/supunlakmal/hash-calendar?tab=readme-ov-file#json-bridge-jsonhtml"
code = "https://github.com/supunlakmal/hash-calendar"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "30M"
ram.build = "0M"
ram.runtime = "0M"


[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/hash-calendar"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/supunlakmal/hash-calendar/archive/eeebbb6b931ab074e09912861299e887cf121017.tar.gz"
        sha256 = "c8624a7ac270cf8b9d8f8f221c1efa1c7e93fe288b15667356231769075a9202"
        extract = true
        in_subdir = true
        autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"
