#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace

pushd "$install_dir"
    # Remove Google Analytics tracking
    sed -i '/<script/{:Loop;N;/\n\s*<\/script>/!bLoop;/gtag/d}' index.html #remove <script> blocks containing 'gtag'

    # Replace CDN links with local files
    ynh_replace --match="https://cdnjs.cloudflare.com/ajax/" --replace="" --file="index.html"
    ynh_replace --match="https://fonts.googleapis.com/css2?family=Fraunces:wght@400;600;700&family=Space+Grotesk:wght@400;500;600&display=swap" --replace="local-webfonts.css" --file="index.html"
    sed -i '/https:\/\/fonts\.g/d' index.html #match both fonts.googleapis.com and fonts.gstatic.com

    # Update privacy policy
    sed -i '/<h2>3\. Analytics<\/h2>/,/<h2>4\. Third-Party Requests<\/h2>/ { /<h2>3\. Analytics<\/h2>/! { /<h2>4\. Third-Party Requests<\/h2>/!d } }' privacy.html #remove all lines between headings 3 and 4, excluding headings
    sed -i '/<h2>3\. Analytics<\/h2>/a \ \ \ \ \ \ <p>This self-hosted instance of hash-calendar does not perform any user tracking.<\/p>' privacy.html
    sed -i '/<h2>4\. Third-Party Requests<\/h2>/,/<h2>5\. Encryption and Security<\/h2>/ { /<h2>4\. Third-Party Requests<\/h2>/! { /<h2>5\. Encryption and Security<\/h2>/!d } }' privacy.html  #remove all lines between headings 4 and 5, excluding headings
    sed -i '/<h2>4\. Third-Party Requests<\/h2>/a \ \ \ \ \ \ <p>This self-hosted instance of hash-calendar does not perform any third-party requests.<\/p>' privacy.html
    ynh_replace --match="<li>Use browser privacy controls or blockers to limit analytics.</li>\n" --replace="" --file="privacy.html"
popd

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
